### ISSUE TITLE
Demo not working

### ISSUE THREAD

**Issue by rogerhendriks** [syncfusion/ej2-javascript-samples#7]
Repro path:

- checked out with github desktop.
- opened cmd on W10
- cd directory
- npm install 
- npm run serve > output
[11:17:00] Using gulpfile ~\Documents\GitHub\ej2-javascript-samples\gulpfile.js
[11:17:00] Starting 'ship-deps'...
[11:17:00] Finished 'ship-deps' after 183 ms
[11:17:00] Starting 'build'...
[11:17:00] Starting 'process-api'...
Unable to access file json for undefined
Unable to access file json for undefined
Unable to access file json for undefined
Unable to access file json for undefined
Unable to access file json for undefined
Unable to access file json for undefined
Unable to access file json for undefined
Unable to access file json for undefined
Unable to access file json for undefined
Unable to access file json for undefined
Unable to access file json for undefined
Unable to access file json for undefined
Unable to access file json for undefined
Unable to access file json for undefined
Unable to access file json for undefined
Unable to access file json for undefined
Unable to access file json for undefined
Unable to access file json for undefined
Unable to access file json for undefined
Unable to access file json for undefined
Unable to access file json for undefined
[11:17:00] Finished 'process-api' after 620 ms
[11:17:00] Starting 'combine-samplelist'...
(node:12580) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
[11:17:01] Finished 'combine-samplelist' after 459 ms
[11:17:01] Starting 'bundle'...
[11:17:02] Version: webpack 2.5.1
                  Asset     Size  Chunks             Chunk Names
src/common/index.min.js  31.6 kB       0  [emitted]  src/common/index.min
[11:17:02] Finished 'bundle' after 795 ms
[11:17:02] Starting 'plnkr-json'...
[11:17:11] Finished 'plnkr-json' after 9.71 s
[11:17:11] Finished 'build' after 12 s
[11:17:11] Starting 'serve'...
[Browsersync] Access URLs:
 -----------------------------------
    Local: "http://localhost:3000"
 -----------------------------------
[Browsersync] Serving files from: ./
[11:17:13] Finished 'serve' after 1.35 s

**Problems:**
- 404 manifest
- pending forever call

![image](https://user-images.githubusercontent.com/2770762/58746528-77e88f00-845f-11e9-944f-188b901d55e8.png)

**Comment by jesusarockias** [comment]
Hi @rogerhendriks,

Sorry for the inconvenience caused.

We are currently checking this and update you further detail on June 06, 2019, and we appreciate your patience until then.

Regards,
Jesus Arockia Sankaran S

**Comment by jesusarockias** [comment]
Hi @rogerhendriks,

Thanks for your patience.

We solved the reported problem in the source of the EJ2 JavaScript GitHub samples and we insist that you pull the latest changes to update your repository.

If you need further assistance in this, please let us know.

Regards,
Jesus Arockia Sankaran S

**Comment by rogerhendriks** [comment]
Download new clone, still getting this in Chrome on W10:
![image](https://user-images.githubusercontent.com/2770762/59978172-e2619a80-95d9-11e9-8456-5c297bfd5f6d.png)

**Comment by nunoffribeiro** [comment]
I cant run cloned project. 

"crossroads.js:111 Uncaught TypeError: Cannot read property 'Signal' of undefined"

and 

"Uncaught (in promise) ReferenceError: crossroads is not defined"

**Comment by GOKUL3897** [comment]
Hi @rogerhendriks / @nunoffribeiro,

Sorry for the delay caused,

We have resolved your reported issue at our end and the changes have also been updated. Now you can access the working sample.

Please let us know if you have any queries.

Regards,
Gokul

**Comment by syncsiva** [comment]
This issue has been resolved and has not had any activity for 1 day. Closing for housekeeping purposes. Please feel free to reopen if you have any further queries.
